name: the4m_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.0
  intl: ^0.18.0
  image_picker: ^1.0.4
  cloud_firestore: ^4.15.4
  firebase_core: ^2.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "lib/assets/images/Logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Sriracha
      fonts:
        - asset: lib/assets/fonts/Sriracha-Regular.ttf
    - family: Bodoni_Italic
      fonts:
        - asset: lib/assets/fonts/BodoniModa-Italic-VariableFont_opsz,wght.ttf
    - family: TenorSans
      fonts:
        - asset: lib/assets/fonts/TenorSans-Regular.ttf
    - family: NotoSerif
      fonts:
        - asset: lib/assets/fonts/NotoSerif-Italic-VariableFont_wdth,wght.ttf
    - family: NotoSerif_2
      fonts:
        - asset: lib/assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/videos/
